import datetime

def export_markdown(links, collection_name, filepath):
    """
    Exports a list of links to a GitHub-friendly README Markdown format.
    """
    title = collection_name if collection_name else "Saved Links"
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"# {title}\n\n")
        f.write(f"A curated collection of useful resources, generated by [LinkVault](#) on {datetime.datetime.now().strftime('%Y-%m-%d')}.\n\n")
        
        f.write("## 📚 Resources\n\n")
        f.write("| Resource | Type | Collection | Description |\n")
        f.write("|---|---|---|---|\n")
        
        for link in links:
            title_text = (link.title or 'Untitled').replace('|', '-')
            type_text = (link.link_type or '').replace('|', '-')
            col_text = link.collection.name if link.collection else '-'
            desc_text = (link.description or '').replace('\n', ' ').replace('|', '-')
            # Truncate description for table
            if len(desc_text) > 50:
                desc_text = desc_text[:47] + '...'
                
            f.write(f"| [{title_text}]({link.url}) | {type_text} | {col_text} | {desc_text} |\n")
            
        f.write("\n## 🔗 Links Detail\n\n")
        
        for link in links:
            f.write(f"### {link.title or 'Untitled'}\n\n")
            f.write(f"**URL:** {link.url}\n\n")
            if link.link_type:
                f.write(f"**Type:** {link.link_type}\n\n")
            if link.tags:
                tag_str = ", ".join(f"`{tag.name}`" for tag in link.tags)
                f.write(f"**Tags:** {tag_str}\n\n")
            if link.description:
                f.write(f"{link.description}\n\n")
            f.write("---\n\n")
            
    return filepath
